# Generated by Django 3.2.8 on 2022-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinee',
            name='username',
            field=models.CharField(default=122, max_length=30),
            preserve_default=False,
        ),
    ]
