# Generated by Django 3.2.8 on 2022-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_personal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
